services:
  wintercode:
    container_name: wintercode
    build:
      context: ./main
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./shared/.env.prod
    volumes:
      - /home/wintercode/backup/wintercode:/app/uploads
    ports:
      - "4000:4000"
    networks:
      - frostNet
    depends_on:
      - mongo-wintercode

  mongo-wintercode:
    container_name: mongo-wintercode
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: wintercode-db
    volumes:
      - /home/wintercode/backup/wintercode:/data/db
    ports:
      - "27017:27017"
    networks:
      - frostNet

networks:
  frostNet:
    driver: bridge
    attachable: true
# correct deployment
