apiVersion: apps/v1
kind: Deployment
metadata:
  name: wintercode
  labels:
    app: wintercode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wintercode
  template:
    metadata:
      labels:
        app: wintercode
    spec:
      containers:
        - name: wintercode
          image: wintercodenkjj/wintercode-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "dev"
            - name: PORT
              value: "5000"
            - name: FRONTEND_URL
              value: "http://localhost:3000"
            - name: PAWAPAY_BASE_URL
              valueFrom:
                secretKeyRef:
                    name: wintercode-secrets
                    key: PAWAPAY_API_URL
            - name: PAWAPAY_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: PAWAPAY_API_TOKEN
            - name: MAIN_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: JWT_SECRET
            - name: LOG_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: JWT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: JWT_SECRET
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: SMTP_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: DB_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: wintercode-secrets
                  key: SMTP_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: wintercode-service
spec:
  selector:
    app: wintercode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Or NodePort if you prefer
