-- AlterTable
ALTER TABLE `ads` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `blog` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `contact` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `faq` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `offer` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `product` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `project` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `review` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `subscriber` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `teammember` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'PUBLISHED', 'ARCHIVED', 'PENDING', 'RESOLVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'HALTED') NOT NULL DEFAULT 'ACTIVE';
